"""Static HTML report for sharing without Streamlit.

Generates a single, self-contained HTML page summarizing per-group metrics and
discrepancy breakdowns. Designed to be friendly to email / GitHub Pages / a
quick artifact handoff. Uses Jinja2 if available; otherwise falls back to a
minimal hand-rolled template so the dependency stays optional.
"""

from __future__ import annotations

from html import escape
from pathlib import Path

from signalyze.analytics import GroupMetrics, iter_group_metrics
from signalyze.compare import compute_discrepancies
from signalyze.storage import Database


def render_html_report(
    *,
    db: Database,
    output_path: Path,
    title: str = "Signalyze report",
    start_utc: str | None = None,
    end_utc: str | None = None,
) -> Path:
    metrics = sorted(
        iter_group_metrics(db=db, start_utc=start_utc, end_utc=end_utc),
        key=lambda m: -(m.actual_win_rate or 0.0),
    )
    discrepancies = compute_discrepancies(db=db)
    categories: dict[str, int] = {}
    for row in discrepancies:
        categories[row.category.value] = categories.get(row.category.value, 0) + 1

    html_doc = _render(
        title=title,
        metrics=metrics,
        categories=categories,
        start_utc=start_utc,
        end_utc=end_utc,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html_doc, encoding="utf-8")
    return output_path


def _render(
    *,
    title: str,
    metrics: list[GroupMetrics],
    categories: dict[str, int],
    start_utc: str | None,
    end_utc: str | None,
) -> str:
    rows = "\n".join(_row(m) for m in metrics)
    cat_rows = "\n".join(
        f"<tr><td>{escape(cat)}</td><td>{count}</td></tr>"
        for cat, count in sorted(categories.items(), key=lambda kv: -kv[1])
    )
    window = ""
    if start_utc or end_utc:
        window = (
            f"<p class='muted'>Window: {escape(start_utc or '-')} → "
            f"{escape(end_utc or '-')}</p>"
        )

    return f"""<!doctype html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<title>{escape(title)}</title>
<style>
  body {{ font-family: system-ui, -apple-system, Segoe UI, Helvetica, Arial, sans-serif;
          color: #1a202c; max-width: 1100px; margin: 2em auto; padding: 0 1em; }}
  h1 {{ font-size: 1.6em; }}
  .muted {{ color: #555; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 2em; }}
  th, td {{ border-bottom: 1px solid #e2e8f0; padding: 6px 10px; text-align: right; }}
  th:first-child, td:first-child {{ text-align: left; }}
  th {{ background: #edf2f7; }}
  .ok {{ color: #2f855a; }}
  .gap-pos {{ color: #c53030; font-weight: 600; }}
  .gap-neg {{ color: #2b6cb0; font-weight: 600; }}
  .num {{ font-variant-numeric: tabular-nums; }}
</style>
</head>
<body>
<h1>{escape(title)}</h1>
{window}

<h2>Per-group performance</h2>
<table>
  <thead>
    <tr>
      <th>Group</th><th>Signals</th>
      <th>Reported win%</th><th>Actual win%</th><th>Gap</th>
      <th>Avg pips</th><th>Avg RR</th>
      <th>Ambiguous bars</th><th>No market data</th>
    </tr>
  </thead>
  <tbody>
    {rows}
  </tbody>
</table>

<h2>Discrepancy categories</h2>
<table>
  <thead><tr><th>Category</th><th>Signals</th></tr></thead>
  <tbody>
    {cat_rows}
  </tbody>
</table>

<p class='muted'>Generated by Signalyze. Re-run <code>signalyze report html</code> to refresh.</p>
</body>
</html>
"""


def _row(m: GroupMetrics) -> str:
    rep = (
        f"{m.reported_win_rate * 100:.1f}%"
        if m.reported_win_rate is not None
        else "n/a"
    )
    act = (
        f"{m.actual_win_rate * 100:.1f}%"
        if m.actual_win_rate is not None
        else "n/a"
    )
    if m.win_rate_gap is None:
        gap_html = "<td>n/a</td>"
    else:
        gap_pct = m.win_rate_gap * 100
        css = "gap-pos" if gap_pct > 0 else "gap-neg"
        gap_html = f"<td class='{css}'>{gap_pct:+.1f}</td>"

    pips = f"{m.avg_realized_pips:.1f}" if m.avg_realized_pips is not None else "n/a"
    rr = f"{m.avg_realized_rr:.2f}" if m.avg_realized_rr is not None else "n/a"

    return (
        f"<tr>"
        f"<td>{escape(m.group_id)}</td>"
        f"<td class='num'>{m.n_signals}</td>"
        f"<td class='num'>{rep}</td>"
        f"<td class='num'>{act}</td>"
        f"{gap_html}"
        f"<td class='num'>{pips}</td>"
        f"<td class='num'>{rr}</td>"
        f"<td class='num'>{m.ambiguous_bars}</td>"
        f"<td class='num'>{m.insufficient_data}</td>"
        f"</tr>"
    )
